### ISSUE TITLE
Server Issue

### ISSUE THREAD

**Issue by 4mildav** [thesarlaacsweep/radioactiveblocks#13]
Having an issue with the mod when used on a server. It seems to crash when crafting a sword or shovel. Crash report is below for your reference. (forge-1.16.1-32.0.88)

[30Jul2020 21:08:15.261] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.NoSuchMethodError: net.minecraft.enchantment.Enchantment.func_185262_c(I)Lnet/minecraft/enchantment/Enchantment;
	at com.thesarlaacsweep.radioactiveblocks.items.RadioactiveSwordItem.func_77622_d(RadioactiveSwordItem.java:32) ~[?:4.2.0-1.16.1-32.0.25]
	at net.minecraft.item.ItemStack.func_77980_a(ItemStack.java:438) ~[?:?]
	at net.minecraft.inventory.container.CraftingResultSlot.func_75208_c(CraftingResultSlot.java:45) ~[?:?]
	at net.minecraft.inventory.container.CraftingResultSlot.func_190901_a(CraftingResultSlot.java:57) ~[?:?]
	at net.minecraft.inventory.container.Container.func_241440_b_(Container.java:292) ~[?:?]
	at net.minecraft.inventory.container.Container.func_184996_a(Container.java:160) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147351_a(ServerPlayNetHandler.java:1187) ~[?:?]
	at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:34) ~[?:?]
	at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:735) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:157) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:718) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:712) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:698) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:647) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

**Comment by thesarlaacsweep** [comment]
It, potentially, maybe because you're on a later version of Forge than what the mod is at currently.

Your Forge: forge-1.16.1-32.0.88

Radioactive Blocks Forge: forge-1.16.1-32.0.25

I'll test this once I have the opportunity to do so. Expect a resolution within 1-2 weeks. Thank you

**Comment by thesarlaacsweep** [comment]
I can confirm that this is not a Forge mismatch issue. This mod has not been tested on servers yet anyhow.

What needs to happen to support server usage of Radioactive Blocks:

- Ore generation only happens in the client. Needs to pass the world gen to the server instance to spawn ores.
- Block/Item registries need to be persisted to the server side.
- Recipes need to be persisted to the server side.
- Configurations need to support the server.
- EventRegistry needs to be passed onto the server.

**Comment by thesarlaacsweep** [comment]
Server implementation is a somewhat complex issue. The target date for completion of support of servers for versions `1.14.x` `1.15.x` `1.16.x` is SEP 26 2020.

**Comment by thesarlaacsweep** [comment]
The underlying issue had to do with the fact that enchanting upon item creation is a client-only implementation. I was not checking for the side in the `onCreation` call within each tool/weapon class. This has been fixed but the side-effect is that server games will not get these tool/weapon enchantments on creation.

I'll leave issue #14 open and update this to investigate if there is a way, via networking, that I can add this feature back in to support server game play.

**Comment by thesarlaacsweep** [comment]
@4mildav You should be able to update your server with the new files on https://www.curseforge.com/minecraft/mc-mods/radioactive-blocks or if you use Twitch just update there by updating from the mod's file listings.
